### ISSUE TITLE
Pretrained model jp-en

### ISSUE THREAD

**Issue by kenziehong** [Mao-KU/JASS#1]
Hi,
I used pretrained model with 
a sentence in paper https://www.aclweb.org/anthology/2020.lrec-1.454.pdf and 
onmt_translate -model  in https://github.com/OpenNMT/OpenNMT-py, 
but it didn't work well https://i.imgur.com/fTNWZgM.png like the paper.

Do I miss something?

**Comment by Mao-KU** [comment]
Thanks for your question.
Sorry for the confusing example in the paper.
Before feeding it the model, you might have to tokenize the ja sentence by using the BPE model.
Also, we use this kind of the tasks to do the pre-training, but it does not mean the pre-trained model can do the translation.
You also might have to fine-tune it by NMT tasks.

We plan to release the newly pre-trained ja-en, ja-zh (on 2 domains), en-ko models in the future.

**Comment by Mao-KU** [comment]
I closed this issue.
If you have further questions, please reopen the issue
